nome = input('Digite seu nome: ')
sobrenome = input('Digite seu sobrenome: ')
dataNascimento = input('Digite sua data de nascimento: ')
idade = int(input('Digite sua idade: '))
endereco = str(input('Digite seu endereço: '))
enderecoComercial = str(input('Digite seu endereço Comercial: '))
cfp = input('Digite seu CPF, somente números: ' )
telefone = input('Digite seu telefone Fixo: ')
telefoneCelular = input('Digite seu telefone Celular: ')
email = str(input('Digite seu email: '))

print('Nome:',nome, sobrenome)
print('Data de nascimento:', dataNascimento)
print('Sua idade:', idade)
print('Endereço:', endereco)
print('Endereço Comercial:', enderecoComercial)
print('CPF:', cfp)
print('Telefone Fixo:', telefone)
print('Telefone Celular:', telefoneCelular)
print('Email:', email)
